const fs = require('fs');
const path = require('path');
const { speakText } = require('../voice/voice_manager'); // Adjust this import based on your exact function name
const { postToActiveChannel } = require('../images/image_gen_manager');

const dataDir = path.join(__dirname, '..', '..', 'temp_data');
const transcriptPath = path.join(dataDir, 'transcript_log.txt');

// Hoisted to module scope (rather than inline in each start*() function below) so index.js can
// import the exact same strings and pre-generate their TTS audio once at startup (see
// voice_manager.js pregenerateStaticAudio()) - the cache is keyed by exact text, so the prompt
// actually spoken here must match what was pre-generated byte-for-byte. Both explicitly name the
// phrase that ends the phase ("we're done") since SESSION_ZERO_FINISH_REGEX below accepts several
// equivalent phrasings but never told players any of them - leaving it to guesswork.
const SESSION_ZERO_PROMPT = "Please give me prompts and ideas for the world and its lore. Say \"we're done\" when you're finished.";
const CHARACTER_INTRO_PROMPT = "Now, going round the table - if you've already linked a D&D Beyond character on the dashboard, just tell me what they're doing as the scene opens. Otherwise, tell me your name, your character's name, a brief description of them, and what they're doing as the scene opens. Once everyone's introduced themselves, say \"we're done\" to begin the adventure.";

let sessionZeroActive = false;
let sessionZeroBuffer = [];

function ensureDataDirectories() {
    fs.mkdirSync(dataDir, { recursive: true });
}

// --- Session Zero State Management ---

function startSessionZero() {
    sessionZeroActive = true;
    sessionZeroBuffer = [];

    const promptText = SESSION_ZERO_PROMPT;
    const timestamp = new Date().toISOString();
    const broadcastMsg = `[${timestamp}] [DaDAA] ${promptText}\n`;

    try {
        ensureDataDirectories();
        fs.appendFileSync(transcriptPath, broadcastMsg, 'utf8');

        speakText(promptText);
        postToActiveChannel({ content: promptText });
    } catch (e) {
        console.warn('-> Could not write to transcript log or play audio', e.message);
    }

    console.log('-> Session Zero started. Listening for world ideas...');
}

function isSessionZeroActive() {
    return sessionZeroActive;
}

function addSessionZeroInput(source, text) {
    if (!sessionZeroActive) return;
    sessionZeroBuffer.push(`[${source}]: ${text}`);
}

function endSessionZero() {
    sessionZeroActive = false;
    const compiledIdeas = sessionZeroBuffer.join('\n');
    sessionZeroBuffer = [];
    return compiledIdeas;
}

// --- Character Introduction State Management ---
// Runs once per campaign, after the campaign seed is generated and read aloud but before
// Session 1's opening event - each player introduces their name, their character, and what
// that character is doing as the scene opens. Buffered the same way Session Zero is above;
// index.js parses the compiled buffer with the LLM once everyone signals they're done, then
// binds each Discord user to their character via character_manager.js bindCharacter().

let characterIntroActive = false;
let characterIntroBuffer = [];

function startCharacterIntros() {
    characterIntroActive = true;
    characterIntroBuffer = [];

    const promptText = CHARACTER_INTRO_PROMPT;
    const timestamp = new Date().toISOString();
    const broadcastMsg = `[${timestamp}] [DaDAA] ${promptText}\n`;

    try {
        ensureDataDirectories();
        fs.appendFileSync(transcriptPath, broadcastMsg, 'utf8');

        speakText(promptText);
        postToActiveChannel({ content: promptText });
    } catch (e) {
        console.warn('-> Could not write to transcript log or play audio', e.message);
    }

    console.log('-> Character introductions started. Listening for players...');
}

function isCharacterIntroActive() {
    return characterIntroActive;
}

function addCharacterIntroInput(source, text) {
    if (!characterIntroActive) return;
    characterIntroBuffer.push(`[${source}]: ${text}`);
}

function endCharacterIntros() {
    characterIntroActive = false;
    const compiledIntros = characterIntroBuffer.join('\n');
    characterIntroBuffer = [];
    return compiledIntros;
}

module.exports = {
    startSessionZero,
    isSessionZeroActive,
    addSessionZeroInput,
    endSessionZero,
    startCharacterIntros,
    isCharacterIntroActive,
    addCharacterIntroInput,
    endCharacterIntros,
    SESSION_ZERO_PROMPT,
    CHARACTER_INTRO_PROMPT
};
